spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
  #context-path: /SpringcloudDemo
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.demo.entity #所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml               #mapper映射文件
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client                    #注册名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://192.168.0.158:3306/cloudDB01  #数据库连接
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                   #数据库连接池的最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: /templates
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
    instance-id: microservicecloud-dept8001 #设置服务别名
  client:
    service-url:
     #单机版 defaultZone: http://localhost:7001/eureka/
     defaultZone: http://eureka7001.com:7001/eureka
#配置微服务信息
info:
  app.name: SpringcloudDemo
  company-name: www.baidu.com
  bulid.artifactId: aa
  bulid.version: bb
---
server:
  port: 8001
  #context-path: /SpringcloudDemo
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.demo.entity #所有entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml               #mapper映射文件
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client                    #注册名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://192.168.0.158:3306/cloudDB02  #数据库连接
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                   #数据库连接池的最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: /templates
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
    instance-id: microservicecloud-dept8001 #设置服务别名
  client:
    service-url:
     #单机版 defaultZone: http://localhost:7001/eureka/
     defaultZone: http://eureka7001.com:7001/eureka
#配置微服务信息
info:
  app.name: SpringcloudDemo
  company-name: www.baidu.com
  bulid.artifactId: aa
  bulid.version: bb